name: ChaosCraft
main: io.github.DDSloan96.ChaosCraft.ChaosCraft
version: 0.2.2

commands:
  slap:
    description: Slaps you to the moon
    usage: /<command> [player]
  h5:
   description: High Fives the player mentioned
    usage:/<command> [player]
  basscannon:
    description: Kicks Player off server
    usage: /<command> [player]